name: DemoJWT CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  deploy: 

    runs-on: ubuntu-latest
    needs: test
    if: success() && github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '**/appsettings.json'
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.DB_CONNECTION_STRING}}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "demo-jwt-netcore"
          heroku_email: "migueldossantos011@gmail.com"
          usedocker: true
